# Generated by Django 4.1.2 on 2022-10-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='dt_inicio',
            new_name='data_inicio',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='dt_termino',
            new_name='data_termino',
        ),
    ]
