# Generated by Django 4.1.2 on 2022-12-18 16:53

from django.db import migrations, models
import django.db.models.deletion
import flows.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, max_length=400, null=True, verbose_name='descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='número')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, max_length=400, null=True, verbose_name='descrição')),
                ('data_inicio', models.DateField(verbose_name='data de início')),
                ('data_finalizacao', models.DateTimeField(validators=[flows.validators.validate_date_is_today_or_after], verbose_name='data de finalização')),
                ('ativa', models.BooleanField(default=False)),
                ('gameficada', models.BooleanField(default=False)),
                ('fluxo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flows.fluxo')),
            ],
        ),
    ]
