# Generated by Django 4.1.2 on 2022-12-18 21:05

from django.db import migrations, models
import flows.validators


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapa',
            options={'ordering': ['numero', 'data_inicio']},
        ),
        migrations.AlterField(
            model_name='etapa',
            name='data_finalizacao',
            field=models.DateField(validators=[flows.validators.validate_date_is_today_or_after], verbose_name='data de finalização'),
        ),
    ]
