# Generated by Django 4.1.2 on 2022-12-02 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artefato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('nome', models.CharField(max_length=70)),
                ('situacao', models.CharField(max_length=25)),
                ('data_entrega', models.DateField(verbose_name='data de entrega')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.projeto')),
            ],
        ),
    ]
